<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
    <link name = "camera_link">
        <visual>
            <geometry>
                <box size="0.01 0.01 0.01"/>
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <material name = "black"/>
        </visual>
        <collision>
            <geometry>
                <box size="0.01 0.01 0.01"/>
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <material name = "black"/>
        </collision>

    </link>

    <joint name="base_to_camera_joint" type="fixed">
        <parent link="base_link"/>
        <child link="camera_link"/>
        <origin xyz="${base_length/2.0} 0 ${base_height}" rpy="0 0 0"/>
    </joint>

    <gazebo reference="camera_link">
        <material>Gazebo/Red</material>
        <sensor name="camera_sensor" type="camera">
            <pose>0 0 0 0 0 0 0</pose>
            <visualize>true</visualize>
            <update_rate>10.0</update_rate>
            <plugin name="camera_plugin" filename="libgazebo_ros_camera.so">
                
                
          
                <!-- Set camera name. If empty, defaults to sensor name -->
                <camera_name>car_camera</camera_name>
          
                <!-- Set TF frame name. If empty, defaults to link name -->
                <frame_name>camera_link</frame_name>
          

              </plugin>
        </sensor>
        
    </gazebo>
    
</robot>